# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - MONGODB_URL=mongodb://user:password@mongodb:27017/lbc
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: lbc
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
      # This volume permits to automatically init MongoDB database
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - node-network

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local

networks:
  node-network:
    driver: bridge
