# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - MONGODB_URL=mongodb://user:password@mongodb:27017/lbc
      # DATABASE_URL: postgresql://admin:password@db:5432/articles
    depends_on:
      # - db
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:6.0-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge


#   db:
#     image: postgres:15-alpine
#     restart: always
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     expose:
#       - 5432
#     environment:
#       - POSTGRES_USER=admin
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=articles

# volumes:
#   postgres_data:
